application: delicious-api
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: 2.5.1
- name: lxml
  version: 2.3